### ISSUE TITLE
Could I find the tex source for pencil-code manual?

### ISSUE THREAD

**Issue by WenyinWei** [pencil-code/website#1]
I am a new user from China, attracted by pencil-code's strong power. I want to translate the manual to Chinese. Would you mind telling me where the tex is?

**Comment by xiang-yu** [comment]
Dear Wenyin,

Glad to hear you would like to translate the manual to Chinese!
As Dhruba suggested, reading the manual is a very good start.
Did you already use Pencil Code?

Would you mind communicating with us with your Tsinghua email account?
Which group are you working at Tsinghua?

Here are my email addresses,
xiang.yu.li.phy@gmail.com
xiang.yu.li@su.se

Please let me know if you need help with Pencil Code.

Cheers,

Xiangyu




Best regards,

Xiangyu

Xiang-Yu Li
Visiting Ph.D. candidate at LASP&JILA
Ph.D. Candidate
Nordita, KTH & Stockholm University
Department of Meteorology, Stockholm University
106 91 Stockholm
Sweden
